### ISSUE TITLE
 Unauthorized Access to Account Details and Balance via Account Number or Name

### ISSUE THREAD

**Issue by Lohithsurya** [acmpesuecc/Bank-Management-System_hn6#5]
Users are able to access sensitive account details, including the balance, by simply knowing the account number or the account holder's name. This poses a privacy risk, as any user with basic information can view the complete account information without proper authentication or authorization.

Expected Behavior:
Access to sensitive account details, including balance information, should require proper authentication.
Knowing the account number or name should not be sufficient to view full account details.

**Comment by Shaynazg** [comment]
can i please be assigned?

**Comment by Lohithsurya** [comment]
!assign @Shaynazg

**Comment by Lohithsurya** [comment]
@Shaynazg the default time is 30mins show me the progress i will extend the time (show before the time runs out)

**Comment by Gunika-Goel** [comment]
can i be assigned to this please?

**Comment by Lohithsurya** [comment]
!deassign

**Comment by Lohithsurya** [comment]
!assign @Gunika-Goel

**Comment by Gunika-Goel** [comment]
I have sent a pr

**Comment by bwaklog** [comment]
!deassign
