### ISSUE TITLE
Feature Request: Add Money Transfer Functionality Between Two Accounts

### ISSUE THREAD

**Issue by Lohithsurya** [acmpesuecc/Bank-Management-System_hn6#6]
Implement a new feature that allows users to transfer money between two accounts within the system. This feature should enable users to initiate a transfer by providing the necessary details of both the sending and receiving accounts, ensuring a secure and user-friendly experience.

Making sure it follows all ACID properties gives extra points

**Comment by jmanoj0905** [comment]
Can I be assigned this?

**Comment by Shaynazg** [comment]
can i be assigned?

**Comment by chandan365c** [comment]
hi can you assign this to me?

**Comment by Lohithsurya** [comment]
!assign @jmanoj0905

**Comment by Lohithsurya** [comment]
@jmanoj0905 the default time is 30 mins show me the progress i will extend the time (show it to me before you run out of time)

**Comment by jmanoj0905** [comment]
I will be going for dinner please compensate my time, Thank you.

**Comment by Lohithsurya** [comment]
!deassign

**Comment by Lohithsurya** [comment]
!assign @jmanoj0905

**Comment by Lohithsurya** [comment]
show me the progress as fast as you can

**Comment by jmanoj0905** [comment]
I am back, I need 2 more minutes, please

**Comment by Lohithsurya** [comment]
sure show me the progress before time ends

**Comment by jmanoj0905** [comment]
I have made a pull request, Can you view the progress there?

**Comment by atharv24mittal** [comment]
can i get it assigned?

**Comment by jmanoj0905** [comment]
Can I be assigned this please
